<a href="https://colab.research.google.com/github/WGlegola/Tensorflow-exercises/blob/main/00introduction_tf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.12.0


In [ ]:
tensor = tf.constant([[1,2],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [ ]:
tensor += 10

In [ ]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110, 120],
       [130, 140]], dtype=int32)>

In [ ]:
A = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
B = tf.constant([[1,1],[1,1],[1,1]])
A,B

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 1],
        [1, 1],
        [1, 1]], dtype=int32)>)

In [ ]:
tf.matmul(A,B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  6],
       [15, 15],
       [24, 24]], dtype=int32)>

In [ ]:
A @ B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  6],
       [15, 15],
       [24, 24]], dtype=int32)>

In [ ]:
tf.transpose(A)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int32)>

In [ ]:
tf.matmul(tf.transpose(A),B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[12, 12],
       [15, 15],
       [18, 18]], dtype=int32)>

In [ ]:
tf.tensordot(A,B, axes=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  6],
       [15, 15],
       [24, 24]], dtype=int32)>

In [ ]:
#change from float32 to float16
A = tf.constant([1.2,2.3])

B = tf.cast(A, dtype=tf.float16)
A.dtype,B.dtype


(tf.float32, tf.float16)

In [ ]:
D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
D=tf.constant(np.random.randint(0,100,size=50))
D

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([25, 91, 29,  5, 93, 23, 74, 66, 68, 12, 74, 98, 57, 32, 62, 50, 58,
       26, 79, 94, 30, 50, 47, 59, 55, 97, 69, 23, 44, 30, 39, 56, 66,  8,
       51, 62, 97, 99, 18, 25, 15, 82, 95, 22, 39,  7,  0, 17, 77, 12])>

In [ ]:
tf.reduce_min(D),tf.reduce_max(D),tf.reduce_mean(D),tf.reduce_sum(D)

(<tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=int64, numpy=99>,
 <tf.Tensor: shape=(), dtype=int64, numpy=50>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2507>)

In [ ]:
tf.math.reduce_variance(tf.cast(D,dtype=tf.float32)),tf.math.reduce_std(tf.cast(D,dtype=tf.float32))

(<tf.Tensor: shape=(), dtype=float32, numpy=847.6803>,
 <tf.Tensor: shape=(), dtype=float32, numpy=29.11495>)

In [ ]:
tf.math.argmax(D),D[39],D[tf.math.argmin(D)]

(<tf.Tensor: shape=(), dtype=int64, numpy=37>,
 <tf.Tensor: shape=(), dtype=int64, numpy=25>,
 <tf.Tensor: shape=(), dtype=int64, numpy=0>)

In [ ]:
E=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
E,E.shape

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
 array([[[[[0.4234147 , 0.30390882, 0.37906325, 0.05142629, 0.45152044,
            0.26526737, 0.49995708, 0.09937   , 0.19490111, 0.7925384 ,
            0.4759394 , 0.10671246, 0.9974365 , 0.27932727, 0.62617624,
            0.7194743 , 0.8452337 , 0.27601755, 0.55326223, 0.7471566 ,
            0.59577715, 0.88027275, 0.5995501 , 0.2443006 , 0.02794528,
            0.95444643, 0.72027934, 0.10868239, 0.5462761 , 0.9302006 ,
            0.15758657, 0.378011  , 0.877215  , 0.5867367 , 0.5941081 ,
            0.70217896, 0.9471177 , 0.82889473, 0.8805448 , 0.15096033,
            0.27371204, 0.6705066 , 0.51236415, 0.79329145, 0.7043009 ,
            0.03182173, 0.5598351 , 0.10472679, 0.7705344 , 0.32890093]]]]],
       dtype=float32)>,
 TensorShape([1, 1, 1, 1, 50]))

In [ ]:
tf.squeeze(E).shape

TensorShape([50])

In [ ]:
F_list = [0,1,2]
F=tf.one_hot(F_list,depth=3)
F_list,F

([0, 1, 2],
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=float32)>)

In [ ]:
J = tf.constant(np.array([1.2,.4,4.5]))
J,np.array(J),type(np.array(J))

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1.2, 0.4, 4.5])>,
 array([1.2, 0.4, 4.5]),
 numpy.ndarray)

In [ ]:
J.numpy(),type(J.numpy())

(array([1.2, 0.4, 4.5]), numpy.ndarray)

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
# Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
# Find the shape, rank and size of the tensors you created in 1.
# Create two tensors containing random values between 0 and 1 with shape [5, 300].
# Multiply the two tensors you created in 3 using matrix multiplication.
# Multiply the two tensors you created in 3 using dot product.
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
# Find the min and max values of the tensor you created in 6 along the first axis.
# Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
# Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
# One-hot encode the tensor you created in 9.

In [ ]:
# 1
scalar = tf.constant([10])
vector = tf.constant([1,2])
matrix = tf.constant([[1,2],[3,5]])
scalar,vector,matrix

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 5]], dtype=int32)>)

In [ ]:
# 2
scalar.shape,scalar.ndim,tf.size(scalar).numpy()

(TensorShape([1]), 1, 1)

In [ ]:

vector.shape,vector.ndim,tf.size(vector).numpy()


(TensorShape([2]), 1, 2)

In [ ]:
matrix.shape,matrix.ndim,tf.size(matrix).numpy()

(TensorShape([2, 2]), 2, 4)

In [ ]:
# 3
random1 = tf.random.uniform(shape=(5,300),maxval=1)
random2 = tf.random.uniform(shape=(5,300),maxval=1)


In [ ]:
random1,random2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.9190773 , 0.57346547, 0.7760763 , ..., 0.7571049 , 0.6274246 ,
         0.07287765],
        [0.7661929 , 0.4817481 , 0.73215234, ..., 0.7578163 , 0.98815084,
         0.78961027],
        [0.79570925, 0.6577941 , 0.07583296, ..., 0.51806307, 0.54283   ,
         0.6668751 ],
        [0.26138914, 0.40039217, 0.19400525, ..., 0.45538294, 0.6334616 ,
         0.6510711 ],
        [0.85182214, 0.2483778 , 0.48579836, ..., 0.3950882 , 0.9351417 ,
         0.44450343]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.34612453, 0.5260439 , 0.9482827 , ..., 0.8497437 , 0.88291943,
         0.98135006],
        [0.43876815, 0.501637  , 0.06877649, ..., 0.24785292, 0.19593537,
         0.6389077 ],
        [0.36978567, 0.57916796, 0.24071002, ..., 0.5134491 , 0.4406321 ,
         0.32333803],
        [0.53966165, 0.04638314, 0.14636278, ..., 0.23569596, 0.67106473,
         0.94139576],
        [0.44098

In [ ]:
# 4
random1 @ tf.transpose(random2), tf.matmul(random1, tf.transpose(random2))

(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[72.709755, 72.293915, 77.4892  , 74.155235, 71.491585],
        [74.863335, 75.79539 , 78.721054, 77.78386 , 72.1968  ],
        [71.67435 , 72.30034 , 76.89926 , 74.25073 , 71.69897 ],
        [68.94422 , 72.692116, 80.6844  , 75.87775 , 71.456985],
        [70.79699 , 73.92621 , 76.621826, 75.97294 , 68.59809 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[72.709755, 72.293915, 77.4892  , 74.155235, 71.491585],
        [74.863335, 75.79539 , 78.721054, 77.78386 , 72.1968  ],
        [71.67435 , 72.30034 , 76.89926 , 74.25073 , 71.69897 ],
        [68.94422 , 72.692116, 80.6844  , 75.87775 , 71.456985],
        [70.79699 , 73.92621 , 76.621826, 75.97294 , 68.59809 ]],
       dtype=float32)>)

In [ ]:
# 5
tf.tensordot(random1,tf.transpose(random2),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.709755, 72.293915, 77.4892  , 74.155235, 71.491585],
       [74.863335, 75.79539 , 78.721054, 77.78386 , 72.1968  ],
       [71.67435 , 72.30034 , 76.89926 , 74.25073 , 71.69897 ],
       [68.94422 , 72.692116, 80.6844  , 75.87775 , 71.456985],
       [70.79699 , 73.92621 , 76.621826, 75.97294 , 68.59809 ]],
      dtype=float32)>

In [ ]:
# 6
random3 = tf.random.uniform(shape=(224, 224, 3),maxval=1)
random3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7854955 , 0.53266585, 0.09707367],
        [0.7192024 , 0.26866043, 0.9823816 ],
        [0.57906914, 0.3653401 , 0.23098755],
        ...,
        [0.84284484, 0.16776621, 0.4880247 ],
        [0.1365838 , 0.60847783, 0.40027738],
        [0.84089553, 0.01198876, 0.5473558 ]],

       [[0.73215306, 0.5343356 , 0.01326001],
        [0.06491148, 0.48500562, 0.8061565 ],
        [0.7247349 , 0.5656456 , 0.36863756],
        ...,
        [0.18047845, 0.5394466 , 0.81872463],
        [0.70995486, 0.28689945, 0.37363398],
        [0.93290496, 0.8041836 , 0.8085263 ]],

       [[0.18253624, 0.5981449 , 0.7478882 ],
        [0.7616625 , 0.8713592 , 0.01147461],
        [0.07262409, 0.37055492, 0.48126006],
        ...,
        [0.96187973, 0.07629323, 0.25603855],
        [0.81251514, 0.04076791, 0.47107327],
        [0.17191434, 0.47839403, 0.92790055]],

       ...,

       [[0.03102338, 0.7102891 , 0.20575666],
        [0.31

In [ ]:
# 7
tf.reduce_min(random3),tf.reduce_max(random3)

(<tf.Tensor: shape=(), dtype=float32, numpy=3.0875206e-05>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9999974>)

In [ ]:
# 8
random4 = tf.random.uniform(shape=(1, 224, 224, 3),maxval=1)
random4.shape, tf.squeeze(random4).shape,

(TensorShape([1, 224, 224, 3]), TensorShape([224, 224, 3]))

In [ ]:
# 9
defined = tf.constant([1,2,3,4,5,6,7,8,9,10])
tf.argmin(defined),tf.argmax(defined)

(<tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=int64, numpy=9>)

In [ ]:
# 10
tf.size(defined),tf.one_hot(defined,depth=10),tf.one_hot([0,1,2,3,4,5,6,7,8,9,10],depth=11),

(<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(10, 10), dtype=float32, numpy=
 array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(11, 11), dtype=float32, numpy=
 array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [

In [ ]:
#fin